# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy Miniapp

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: npm ci
    - run: npm run build
    - env:
        MINI_APPS_ACCESS_TOKEN: ${{ secrets.access_token }}
        MINI_APPS_APP_ID: ${{ secrets.app_id }}
    - run: npm run deploy
