name: Deploy Miniapp With Sentry

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: |
          BRANCH_NAME=$(git symbolic-ref --short -q HEAD)
          PACKAGE_VERSION=$(node -p -e "require('./package.json').version")
          COMMIT_VERSION=$(git rev-parse --short HEAD)
          REACT_APP_VERSION=$PACKAGE_VERSION@$BRANCH_NAME-$COMMIT_VERSION
          npm run build
          ./node_modules/.bin/sentry-cli releases new "$REACT_APP_VERSION"
          ./node_modules/.bin/sentry-cli releases files "$REACT_APP_VERSION" upload-sourcemaps --rewrite build/static/js --url-prefix '~/static/js/'
          ./node_modules/.bin/sentry-cli releases set-commits "$REACT_APP_VERSION" --auto
          ./node_modules/.bin/sentry-cli releases finalize "$REACT_APP_VERSION"
          ./node_modules/.bin/sentry-cli releases deploys "$REACT_APP_VERSION" new -e $BRANCH_NAME
          find build/ -type f -regex ".*\.map" -delete
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.sentry_auth_token }}
          SENTRY_ORG: nedzvetskiy
          SENTRY_PROJECT: miniaps-test
      - run: npm run deploy
        env:
          MINI_APPS_ACCESS_TOKEN: ${{ secrets.access_token }}
          MINI_APPS_APP_ID: ${{ secrets.app_id }}
